# Init fails when s3 backend is managed by terragrunt

**stayman** commented *Aug 26, 2020*

@gazprometheus and I were initializing terragrunt in our environment, and we caught onto an issue with generating `backend.tf`

### Terragrunt Version
0.23.34

Essentially, when we follow the example in the documentation for quickstart, with a `terragrunt.hcl` that looks like:
```hcl

terraform {
    source = "<MODULE LOCATION>"
}
remote_state {
    backend = "s3"
    generate = {
        path = "backend.tf"
        if_exists = "overwrite_terragrunt"
    }
    config = {
        encrypt = true
        bucket = "<BUCKET>"
        dynamodb_table = "terraform-state-lock-dynamo"
        region = "us-east-1"
        key = "<PATH>/terraform.tfstate"
    }
}
```

when we execute `AWS_PROFILE=Dev terragrunt init`, we get a series of 403 errors from AWS. However, when we manually include a `backend.tf` as a peer to `terragrunt.hcl` that is otherwise identical to the generated `backend.tf` `terragrunt init` succeeds.

e.g. the following works:
```
module
├── backend.tf
└── terragrunt.hcl
```

where `backend.tf` looks like:

```hcl
terraform {
  backend "s3" {
    bucket         = "<BUCKET>"
    dynamodb_table = "terraform-state-lock-dynamo"
    encrypt        = true
    key            = "<PATH>/terraform.tfstate"
    region         = "us-east-1"
  }
}
```

There is a possiblity this is related to #1129 given that we use aws sso, but I suspect this is not the case given that I am able to init terragrunt successfully with a manually managed `backend.tf`
<br />
***


**yorinasub17** commented *Aug 26, 2020*

Can you share the logs with the 403 errors? There are multiple places where it could 403 and it would help to identify which call is causing it.
***

**stayman** commented *Aug 26, 2020*

```
[terragrunt] [/Users/stayman/dev/repo/Terraform/Dev/uart3] 2020/08/26 14:50:17 Running command: terraform --version
[terragrunt] 2020/08/26 14:50:18 Terraform version: 0.12.29
[terragrunt] 2020/08/26 14:50:18 Reading Terragrunt config file at /Users/stayman/dev/repo/Terraform/Dev/uart3/terragrunt.hcl
[terragrunt] 2020/08/26 14:50:18 WARNING: no double-slash (//) found in source URL /Users/stayman/dev/repo/Terraform/applications/uart3. Relative paths in downloaded Terraform code may not work.
[terragrunt] 2020/08/26 14:50:18 Downloading Terraform configurations from file:///Users/stayman/dev/repo/Terraform/applications/uart3 into /Users/stayman/dev/repo/Terraform/Dev/uart3/.terragrunt-cache/J_spidMlLdjOVeJieqvKHt3VjEg/JDsHmx1DUI0H9dYhP1p_T2Mbbzw
[terragrunt] 2020/08/26 14:50:18 Copying files from /Users/stayman/dev/repo/Terraform/Dev/uart3 into /Users/stayman/dev/repo/Terraform/Dev/uart3/.terragrunt-cache/J_spidMlLdjOVeJieqvKHt3VjEg/JDsHmx1DUI0H9dYhP1p_T2Mbbzw
[terragrunt] 2020/08/26 14:50:18 Setting working directory to /Users/stayman/dev/repo/Terraform/Dev/uart3/.terragrunt-cache/J_spidMlLdjOVeJieqvKHt3VjEg/JDsHmx1DUI0H9dYhP1p_T2Mbbzw
[terragrunt] 2020/08/26 14:50:18 Generated file /Users/stayman/dev/repo/Terraform/Dev/uart3/.terragrunt-cache/J_spidMlLdjOVeJieqvKHt3VjEg/JDsHmx1DUI0H9dYhP1p_T2Mbbzw/backend.tf.
[terragrunt] [/Users/stayman/dev/repo/Terraform/Dev/uart3] 2020/08/26 14:50:18 Initializing remote state for the s3 backend
[terragrunt] 2020/08/26 14:50:18 AccessDenied: Access Denied
        status code: 403, request id: 7DF077B64E41F5FB, host id: pwNRcW+ojqe5tst+TBwfLR67RV40PIhPhhvZYu2tx2cOSv7f2GRSgiUypJdgN991H5wBkyYoCbM=
[terragrunt] 2020/08/26 14:50:18 Unable to determine underlying exit code, so Terragrunt will exit with error code 1
```
***

**yorinasub17** commented *Aug 26, 2020*

Thanks for sharing the logs. It appears that terragrunt is erroring out when trying to check if the remote state bucket exists and if it has the right settings (e.g. if encryption is enabled).

I tried using an `AWS_PROFILE` to see if that was the issue, but I confirmed that terragrunt handles `AWS_PROFILE` correctly.

What permissions are set on the user? Do you by chance have reduced S3 permissions for the s3 bucket set? If so, that may be the conflict as terragrunt needs more permissions than terraform to validate the remote state bucket is configured correctly.
***

**stayman** commented *Aug 26, 2020*

The user has administrator permissions, and when I use terragrunt with a non-terragrunt managed backend the exact same keys I authenticate without any problem. I am also using AWS_PROFILE to identify which user to be, and the only difference between the scenario working and not working is the presence of the `remote_state` block in my `terraform.hcl` managing the creation of the backend file.
***

**yorinasub17** commented *Aug 27, 2020*

Sorry I should have clarified.

The `remote_state` block does more than just generate the backend configuration. It also informs terragrunt that it should automanage the state bucket (see https://terragrunt.gruntwork.io/docs/features/keep-your-remote-state-configuration-dry/#create-remote-state-and-locking-resources-automatically). As part of this, terragrunt internally sets up the AWS SDK Go to inspect your AWS account to see if you have the S3 bucket setup correctly. This includes listing the bucket, checking that it has the necessary attributes, updating the bucket access policy to allow the root user, and checking dynamodb for the lock table. This does more than what terraform does during `init`, which just grabs the state file object, hence there is a difference in the required permissions.

The logs indicate that this is failing in that routine, when terragrunt is running through the checklist of validating if the state bucket is setup correctly, and I was wondering if you may not have the right permissions for modifying that S3 bucket on the user.

If this is ringing any bells, you can disable certain parts of the routine by adding the corresponding `skip` var to the config (see [the docs](https://terragrunt.gruntwork.io/docs/reference/config-blocks-and-attributes/#remote_state) for more details).

Alternatively, you can completely disable the management feature by setting `disable_init` to `true`:

```
remote_state {
    disable_init = true
    backend = "s3"
    generate = {
        path = "backend.tf"
        if_exists = "overwrite_terragrunt"
    }
    config = {
        encrypt = true
        bucket = "<BUCKET>"
        dynamodb_table = "terraform-state-lock-dynamo"
        region = "us-east-1"
        key = "<PATH>/terraform.tfstate"
    }
}
```

Unfortunately, I can't really be of much more help here since I can't reproduce the error using a similar setup. If you or anyone else in the community, can repro this and want to dig in, it would help if you can figure out which function is causing this problem [in here](https://github.com/gruntwork-io/terragrunt/blob/master/remote/remote_state_s3.go#L202).
***

**stayman** commented *Aug 27, 2020*

Thank you for the guidance. setting `disable_init` to true solved the issue. Thank you for the help.
***

