# Occasional failure to init backend when running against many stacks in parallel (e.g. run-all)

**lorengordon** commented *Oct 11, 2022*

We've occasionally seen an error when initializing an S3 backend when using an EC2 instance profile (or Codebuild execution role) and running many stacks in parallel.

```
Error: error configuring S3 Backend: no valid credential sources for S3 Backend found.
Please see https://www.terraform.io/docs/language/settings/backends/s3.html
for more information about providing credentials.
Error: NoCredentialProviders: no valid providers in chain. Deprecated.
For verbose messaging see aws.Config.CredentialsChainVerboseErrors
```

The first "Error" is printed to stdout, so can't be captured in the current retry logic. But the second "Error" line goes to stderr and can be retried by Terragrunt.

What I suspect is happening is some kind of internal rate-limiting in the metadata service, such that the credential retrieval is failing. Instead of a HTTP 429 though, either Terraform or the SDK are just returning an error. Anyway, we've been using a `retryable_errors` config that includes this line for a week now and the error hasn't occurred since (when before it would happen several times a day).

```
  "(?s).*Error: NoCredentialProviders: no valid providers in chain.*",
```


<br />
***


