# Terragrunt Tests Fail in My LocalDev

**josh-padnick** commented *Dec 5, 2016*

Not sure when this started happening and why it's apparently not happening in CI, but Terragrunt tests consistently fail when I run them locally. It's late here, so I'm just recording this but haven't dug into why yet. Here's the test output:

```
[terragrunt] 2016/12/05 01:26:46 Reading Terragrunt config file at /var/folders/g0/0gkdx4sj4qv5gzxfcznscdpw0000gn/T/.terragrunt053106030
[terragrunt] 2016/12/05 01:26:46 Initializing remote state for the s3 backend
Remote state S3 bucket terragrunt-test-bucket-oapzqi does not exist or you don't have permissions to access it. Would you Terragrunt to create it? (y/n)
[terragrunt] 2016/12/05 01:26:46 The non-interactive flag is set to true, so assuming 'yes' for all prompts
[terragrunt] 2016/12/05 01:26:46 Creating S3 bucket terragrunt-test-bucket-oapzqi
[terragrunt] 2016/12/05 01:26:47 S3 bucket terragrunt-test-bucket-oapzqi created.
[terragrunt] 2016/12/05 01:26:47 Enabling versioning on S3 bucket terragrunt-test-bucket-oapzqi
[terragrunt] 2016/12/05 01:26:48 Configuring remote state for the s3 backend
[terragrunt] 2016/12/05 01:26:48 Running command: terraform remote config -backend s3 -backend-config=encrypt=true -backend-config=bucket=terragrunt-test-bucket-oapzqi -backend-config=key=terraform.tfstate -backend-config=region=us-west-2
Initialized blank state with remote state enabled!
Remote state configured and pulled.
[terragrunt] 2016/12/05 01:26:49 Attempting to acquire lock for state file terragrunt-test-fixture in DynamoDB
[terragrunt] 2016/12/05 01:26:49 Lock table terragrunt_locks does not exist in DynamoDB. Will need to create it just this first time.
[terragrunt] 2016/12/05 01:26:49 Creating table terragrunt_locks in DynamoDB
[terragrunt] 2016/12/05 01:26:50 Table terragrunt_locks is not yet in active state. Will check again after 10s.
[terragrunt] 2016/12/05 01:27:00 Success! Table terragrunt_locks is now in active state.
[terragrunt] 2016/12/05 01:27:00 Attempting to create lock item for state file terragrunt-test-fixture in DynamoDB table terragrunt_locks
[terragrunt] 2016/12/05 01:27:00 Lock acquired!
[terragrunt] 2016/12/05 01:27:00 Running command: terraform apply fixture/
data.template_file.test: Refreshing state...

Apply complete! Resources: 0 added, 0 changed, 0 destroyed.

Outputs:

rendered_template =
[terragrunt] 2016/12/05 01:27:01 Attempting to release lock for state file terragrunt-test-fixture in DynamoDB
[terragrunt] 2016/12/05 01:27:01 Lock released!
[terragrunt] 2016/12/05 01:27:03 Reading Terragrunt config file at fixture-lock/.terragrunt
Are you sure you want to acquire a long-term lock? (y/n)
[terragrunt] 2016/12/05 01:27:03 The non-interactive flag is set to true, so assuming 'yes' for all prompts
[terragrunt] 2016/12/05 01:27:03 Acquiring long-term lock. To release the lock, use the release-lock command.
[terragrunt] 2016/12/05 01:27:03 Attempting to acquire lock for state file terragrunt-test-fixture-lock in DynamoDB
[terragrunt] 2016/12/05 01:27:03 Attempting to create lock item for state file terragrunt-test-fixture-lock in DynamoDB table terragrunt_locks
[terragrunt] 2016/12/05 01:27:03 Lock acquired!
[terragrunt] 2016/12/05 01:27:03 Reading Terragrunt config file at fixture-lock/.terragrunt
[terragrunt] 2016/12/05 01:27:03 Attempting to acquire lock for state file terragrunt-test-fixture-lock in DynamoDB
[terragrunt] 2016/12/05 01:27:03 Attempting to create lock item for state file terragrunt-test-fixture-lock in DynamoDB table terragrunt_locks
[terragrunt] 2016/12/05 01:27:03 Someone already has a lock on state file terragrunt-test-fixture-lock! arn:aws:iam::087285199408:user/josh@phoenixdevops.com@10.0.1.9 acquired the lock on 2016-12-05 08:27:03.216425023 +0000 UTC.
Unable to acquire lock for item terragrunt-test-fixture-lock after 1 retries.
exit status 1
FAIL	github.com/gruntwork-io/terragrunt/test	17.631s
```
<br />
***


**josh-padnick** commented *Dec 5, 2016*

Looks like it's happening in CircleCI now, too.
https://circleci.com/gh/gruntwork-io/terragrunt/154

Not positive it's the same test failure but it's the same error message, so probably.
***

**brikis98** commented *Dec 5, 2016*

Were you running this test in parallel with the test in CircleCI? Perhaps we just need to make the lock name unique on each test run.
***

**brikis98** commented *Dec 5, 2016*

Oh, it actually looks like you have a lock stuck on that particular file. Perhaps that happened when terragrunt panicked on you and didn't clean up a lock at the end of a test run. Once we clean that up, the test should pass again. Of course, it would be even safer if we generated a unique lock name per test, but we can do that later.
***

**brikis98** commented *Dec 5, 2016*

Yea, that fixed it
***

