# Alternate messages when lock item or table doesn't exist

**asobrien** commented *Jan 20, 2017*

Fixes #16 

When a non-existent lock is released via `terragrunt release-lock` this will emit a corresponding message indicating that:

```
[terragrunt]  Are you sure you want to release DynamoDB lock for state file .? (y/n) y
[terragrunt] 2017/01/19 20:58:40 Attempting to release lock for state file . in DynamoDB
[terragrunt] 2017/01/19 20:58:40 Nothing to release, specified lock does not exist in table terragrunt_lock_table
```

Additionally, if attempting to release a lock on a non-existent table, the message will reflect this:

```
[terragrunt]  Are you sure you want to release DynamoDB lock for state file .? (y/n) y
[terragrunt] 2017/01/19 20:56:46 Attempting to release lock for state file . in DynamoDB
[terragrunt] 2017/01/19 20:56:47 Table non_existent_table does not exist in DynamoDB!
```

<br />
***


**asobrien** commented *Jan 20, 2017*

I think using custom errors and a separate error method make things a lot clearer. 
***

**asobrien** commented *Jan 22, 2017*

@brikis98 Thanks for comments, I think these commits should address them. 

I moved the error handling for AWS errors resulting from `removeItemFromLockTable` directly into that function. I think it makes much more sense to do it this way, as you had suggested, since these errors are now available to all callers. Also, the redundant call to check for the existence of the table was removed.

With custom errors returned from `removeItemFromLockTable`, rather than suppressing the error as was done previously, this allows the error to bubble up and return a non-zero exit code. For instance:

```
$ terragrunt release-lock
    ...
[terragrunt]  Are you sure you want to release DynamoDB lock for state file .? (y/n) y
[terragrunt] 2017/01/22 14:04:16 Attempting to release lock for state file . in DynamoDB
Item . does not exist in terragrunt_locks DynamoDB table! Original error from AWS: ConditionalCheckFailedException: The conditional request failed
	status code: 400, request id: AIKS88***************************************
[terragrunt] 2017/01/22 14:04:16 Item . does not exist in terragrunt_locks DynamoDB table! Original error from AWS: ConditionalCheckFailedException: The conditional request failed
	status code: 400, request id: AIKS88***************************************
# exit code 1
```

Do you expect that `release-lock` should return non-zero exit codes in the case of an `Item` or `Table` not existing in dynamodb? I would think so. 

It's outside the scope of this PR, but It seems like all errors are getting duplicated since `urfave/cli` will print any error returned by `app.Run` to stderr, and terragrunt handles and logs the error in `checkForErrorsAndExit`. I have some thoughts on how to suppress terragrunt internal errors from being printed by `cli` and having them handled by the terragrunt logger to keep behavior consistent.

As for test output, do you want me to dump the results of the full test suite or just the relevant tests? Here's the output of from the test that was modified:

```
$ go test -v -parallel 128 -run TestWriteAndRemoveItemFromLockTable
[terragrunt] 2017/01/22 14:22:30 Lock table terragrunt_test_R5iMpW does not exist in DynamoDB. Will need to create it just this first time.
[terragrunt] 2017/01/22 14:22:30 Creating table terragrunt_test_R5iMpW in DynamoDB
[terragrunt] 2017/01/22 14:22:30 Table terragrunt_test_R5iMpW is not yet in active state. Will check again after 10s.
[terragrunt] 2017/01/22 14:22:40 Table terragrunt_test_R5iMpW is not yet in active state. Will check again after 10s.
[terragrunt] 2017/01/22 14:22:50 Success! Table terragrunt_test_R5iMpW is now in active state.
--- PASS: TestWriteAndRemoveItemFromLockTable (21.01s)
PASS
ok  	github.com/gruntwork-io/terragrunt/locks/dynamodb	21.017s
```

***

**brikis98** commented *Jan 22, 2017*

> Do you expect that release-lock should return non-zero exit codes in the case of an Item or Table not existing in dynamodb? I would think so.

Yup!

> It's outside the scope of this PR, but It seems like all errors are getting duplicated since urfave/cli will print any error returned by app.Run to stderr, and terragrunt handles and logs the error in checkForErrorsAndExit. I have some thoughts on how to suppress terragrunt internal errors from being printed by cli and having them handled by the terragrunt logger to keep behavior consistent.

Sounds like a bug. If you have an idea how to fix that, another PR would be most welcome :)

> As for test output, do you want me to dump the results of the full test suite or just the relevant tests? 

I ask for it as a sanity check that you did, in fact, run the tests. I can't rely on Circle CI to do it for PRs due to security reasons. Of course, I'm going to merge now and all the tests will run anyway, so we'll see if things are still working shortly.

Thank you for contributing!
***

**brikis98** commented *Jan 22, 2017*

I just created a new release here: https://github.com/gruntwork-io/terragrunt/releases/tag/v0.9.3. If the build passes, the new binaries should show up shortly.
***

